### ISSUE TITLE
why reload methodlist when invoking?

### ISSUE THREAD

**Issue by ericmayc** [cpgf/cpgf#56]
hi @wqking ,
reading the code, I find it will reload methodlist in doInvokeMethodList of gbindcommon.cpp. Though there is some comments, I cannot understand what is the case the "this" pointer may change.

**Comment by wqking** [comment]
Hi，

I can't remember the reason clearly. The code was written about 4~5 years ago.
What I can recall is there is some good reason to do it. If you test to not to reload the method list, some unit tests will fail.

One reason I can think of is, the methods reloading is to deal with assigning methods to variable, such as ```var a = myCppObject.myCppMethod```, and use the variable later.
Another reason probably is to deal with multiple inheritance. When the script binding iterating the method list in the class hierarchy, when it gets to the second base class, it will correct it by selecting the first base class. See how GMetaClassTraveller and selectBoundClass works.

Did you find any performance issue by the methods reloading?

**Comment by ericmayc** [comment]
I have a test on mobile device, the performance is unsatisfactory. one simple JS API cost more than 200 us. there are some hot spots.
1, gv8bind.cpp::bindClassItems::object->SetAccessor,  which spending linear growth, it will cost about dozens us on first call, but cost about 2000 us on thousandth call. 
2, gbindcommon.cpp::loadMethodList  and ,which spending  dozens us.
3, gbindcommon.cpp::doInvokeCallable, whick spending dozens us.

**Comment by wqking** [comment]
Hi

Thanks for the benchmark.

About the performance. cpgf handles general type. Before a method is invoking, the engine does a lot of type converting. So the performance can not be as great as the other engines that does the binding directly, such as ToLua++.
However, I expected the performance in cpgf is decent, though I didn't do any test myself.

It's possible to improve the performance, if we remove some type conversion and/or safety check. But then it's not general any more.

For your first point, gv8bind.cpp::bindClassItems::object->SetAccessor
SetAccessor is called only for static member and to allow the C++ class being inherited from the script. If you don't need either features, you can drop the function (comment it out entirely).
However, the function is only called when a class is bound to the script the first time, and then the class template is cached and the function is not called any more.

**Comment by myocytebd** [comment]
Hi.
How to introspect the real type and content of (void *)instance returned by GMetaClassTraveller.next()?
I am clueless at the caster template magic there.

I tried to study some runtime behavior of loadMethodList. In my run, when it actually change something, it return another (void *)instance.
However the output instance is very far away from the input instance, seems like some wrapped struct?

**Comment by wqking** [comment]
The instance is just the object instance, no any wrapper.
See function GMetaClassTraveller::next, when the traveller finds any base class, it invokes node.metaClass->castToBase to cast the instance to point to base class.
How "far" is the output instance away from the input? Can you check if it points to the base class?

**Comment by myocytebd** [comment]
I found a comment saying that:
"always choose first base because we only support single inheritance in script binding"  

So in case of scriptbind, it only need to support the case that a method mixin-ed from the non-major inheritance tree? (e.g. interface-like classes)
(The "this vs method" compatibility check, since it's single-inheritance, could be supported from script engine.)

Also the whole class could be pre-initialized.
On the major inheritance tree, method objects can be shared, and never has to be reloaded.
On the mixin-ed interfaces, method object could be created per real class x method combo, and record the casting class chain; or for simplicity share a single "always reload" version for the same method.  

This way the method lookup offloads to script engine, and reloading method-list could be saved most of the time.  

> Can you check if it points to the base class?

It is.
I made a silly mistake and took the initial instance from methodData->methodList() as base pointer.

**Comment by wqking** [comment]
You raised some very good points.
If the method reloading is caused by multiple inheritance, we can do some optimization as you described.
I will do some check when I get some free time. Also you are welcome to contribute to the code base. :-)

**Comment by wqking** [comment]
Hi after two years :-)
I open an issues #67 focusing on this issue, I will work on it soon.
