### ISSUE TITLE
A question regarding script binding performance

### ISSUE THREAD

**Issue by Neovet** [cpgf/cpgf#61]
Hi,

I've used luabind for script binding and then found cpgf and it seems so great, because I always planned to add reflection to my game engine.

But there is a little question regarding the performance.

First, I made a benchmark to test the FindMetaMethod+Invoke scenario on i5-3570K for this class:

``` c++
class Test
{
public:
  int func(int a, int b)
  {
    return a + b;
  }
};
```

1) luabind

``` c++
luabind::module(state)
[
  luabind::class_<Test>("Test")
    .def(constructor<>())
    .def("func", &Test::func)
];
```

``` lua
local obj = Test()
for i = 1, 10000000 do
    obj:func(1, 2)
end
```

This code took 1580ms.

2) cpgf

``` c++
cpgf::GDefineMetaClass<Test>
  ::define("Test")
  ._method("func", &CpgfTest::func);

Test obj;
cpgf::GMetaClass* t = cpgf::findMetaClass("Test");
for (int i = 0; i < 10000000; ++i)
{
    cpgf::GMetaMethod* m = t->getMethod("func");
    cpgf::fromVariant<int>(m->invoke(&obj, 1, 2));
}
```

This code took 1135ms, so it's even faster than luabind and I'm happy.

3) cpgf+lua

Modified samples/scriptbind/luabind/constructor.cpp sample - added similar TestObject::func method and bencmarked the last line from next code:

``` c++
TestLuaContext context;
GScopedInterface<IMetaClass> metaClass(context.getService()->findClassByName("testscript::TestObject"));
context.getBinding()->bindClass("TestObject", metaClass.get());
context.doString("a = TestObject()\nfor i = 1, 1000000 do a.func(1, 2) end\n");
```

This code took 61332ms, 38 times slower than luabind. I hope I mistaken somewhere.
Please help, because I would like very much to use your excellent library

**Comment by wqking** [comment]
Hi,

I didn't do any benchmark on the performance yet.

In my opinion, theorically speaking, cpgf should be a little slower than Luabind and ToLua++. This is because that the later is very specified to Lua and C++, while cpgf is very generic and doesn't directly bind and optimize for Lua or any specified script engine. cpgf has to handle all generic situations, which may hit the performance.

However, seems your result of 60 seconds is questionable. I did a quick test same as your third test, the result is about 8 seconds (three times, 8354, 7865, 7911, milliseconds). My system is 
Xeon E3-1225 3.2GHz, 8G RAM, Win7 64, which is quite similar to your i5 system, IMO.
8 seconds should be still slower than Luabind, but it's usable.

My test is also in contructor.cpp, and compiled with VC 2013, Win32 release mode, below is the code snippet,
```
void doTest()
{
	using namespace cpgf;
	using namespace testscript;

	TestLuaContext context;
	context.doString("print(\"Constructor\")");

	GScopedInterface<IMetaClass> metaClass(context.getService()->findClassByName("testscript::TestObject"));
	testCheckAssert(metaClass);
	
	context.getBinding()->bindClass("TestObject", metaClass.get());

	// omitted other test code

	clock_t t = clock();
	context.doString("a = TestObject()\nfor i = 1, 1000000 do a.func(1, 2) end\n");
	t = clock() - t;
	std::cout << t * 1000 / CLOCKS_PER_SEC << std::endl;
	exit(0);
}
```

So, did you compile your code in release mode, and which compiler, GCC?

Recently I'm quite busy on my daily job and my another closed source side project. I wish one day I can have time to do some comprehensive benchmark.

Also please bear in mind, cpgf was optimized to support multiple script engines and generic usage, but not very optimized for performance. So if you find anything to optimize, don't hesitate to contribute to the project. :-)

Thanks for your benchmark and time.

**Comment by Neovet** [comment]
Hi,

Thanks for your time and detailed answer.

"A little slower" would be just perfect considering how many possibilities generic meta-system can provide.
As for the benchmark - I've used Visual Studio 2013 Release mode. But there is a misspelling in the code. Actual number of iterations is 10 000 000, not 1 000 000. For bot luabind and cpgf code. So the difference is really so big, which is frustrating :(
Using both luabind and cpgf would be an overkill maybe.

**Comment by wqking** [comment]
I just noticed the misspelling. So cpgf must be quite slower than Luabind.
I believe there is much potential to improve the performance and I wish I can get a hand on it.
One know issue about the performance is described here,
https://github.com/cpgf/cpgf/issues/56

**Comment by bagobor** [comment]
Just small notice:
You use obj:func(1, 2) in luabind test and a.fun() in cpgf test.
I assume using '.' (dot) leads to more broad search in some global table/map.

(Sorry I just don't have test environment to check my assumption.)

**Comment by bagobor** [comment]
You also may found usefull:
Mini-Review libraries for Reflection in C ++ (translated to English)
https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fhabrahabr.ru%2Fpost%2F257071%2F&edit-text=&act=url

**Comment by wqking** [comment]
Thanks bagobor. cpgf requires using dot instead of colon to invoke Lua method, so it's not a problem.
I read the mini review. Please note that comparing cpgf getMethod and invoke to Luabind is unfair to Luabind. The former is pure C++ code, while the later is Lua/C++ code.

**Comment by Neovet** [comment]
Oh, this is my article. So interesting to meet it here :)
I've added annotation regarding not fair comparison with luabind.

**Comment by Neovet** [comment]
Tried to profile using VTune.
Here is the overall picture - http://take.ms/OxDu1
Some detalisation of callbackInvokeMethodList function - http://take.ms/FZyQt
And same for namedMemberToScript - https://monosnap.com/file/Z8HxlqI3H06pEoIEuzLQfL8lfswDe9

**Comment by bagobor** [comment]
@wqking Thanks for correcting me.

@Neovet сорри не обратил внимание на ник автора статьи. А так да - мир программерский тесен. ))) You may also find useful https://github.com/decimad/luabind-deboostified project. I used it in several projects and it served well. I hope you'll find time to add it to your article.

**Comment by wqking** [comment]
The performance was improved in latest release, though it's still not as fast as any "native" Lua binding engine such as Luabind.
