### ISSUE TITLE
Getting a function pointer from GMetaMethod

### ISSUE THREAD

**Issue by sogartar** [cpgf/cpgf#64]
Hi,
In the reflection library documentation, I could not find how to get the function pointer form GMetaMethod. Does anyone know how to do that?

**Comment by wqking** [comment]
Hi,

You can't get the raw function pointer from meta method. The idea behind the meta method is that it hides the details of the raw functions. Indeed the function held by a meta method may be more complicated than a simple pointer, it can be: a pointer to a global function, a pointer to a member function, or even a functor object which is not a function.

**Comment by sogartar** [comment]
Hi wqking,
I suspected an answer like this. Wouldn't it be nice to be able to do it in the cases where a function pointer can be retrieved in a legal C++ way. For example it is not virtual and it is not inlined. I have looked at the code of how a call is made and all parameters are first wrapped in a GVariant. I would like to avoid this performance hit and make the call directly, because I know in advance the signature of the function and I know I can get a function pointer of it.

**Comment by wqking** [comment]
Hi,

There is a "callback" in GMetaMethodData, which is a GCallback, which is equivalent to std::function.
You may try to use it on your need.
However, such feature can't be added to the library because it breaks the encapsulation and can't be used across modules which compiled by difference C++ compilers.
