### ISSUE TITLE
Tweening Library Small Bug: The target(accessor, fromValue, targetValue) Function Not Working

### ISSUE THREAD

**Issue by nko12** [cpgf/cpgf#66]
I think I've found a bug in the Tweening library, specifically with the GTween class.

If I understand correctly, calling GTween.target(accessor, fromValue, targetValue) should explicitly set both the start and end value of the tweening animation. However, the fromValue is ignored. Instead, the start value is determined from the current value of the object that the accessor references, regardless of calling target(accessor, targetValue) or target(access, fromValue, targetValue).

I am able to reproduce this with the following code.
```CPP
// Initialize the animation
// impl->progressAnimValue = startValue;
impl->progressAnim.target(cpgf::createAccessor(impl.get(), &ProgressBarImpl::progressAnimValue, &ProgressBarImpl::progressAnimValue), startValue, endValue)
    .duration(1.0F)
    .ease(cpgf::LinearEase::easeInOut());
impl->progressAnim.restart();
impl->progressAnim.immediateTick();
```

`impl->progressAnimValue` is the floating point value that I am animating. `startValue` and `endValue` are the start and end values that should be tweened between. If I leave the line `impl->progressAnimValue = startValue` commented out, I get unexpected behavior that I can tell is the result of GTween using the current (wrong) value of impl->progressAnimValue as a starting value, instead of using`startValue`. Uncommenting that line of code results in the expected behavior.

**Comment by wqking** [comment]
Hi,

I just checked the code and the document, seems it was intended behavior (though I cant' remember exactly, I wrote the code about 7 years ago...).
Since you set the getter in the accessor, the tween will use the getter instead of the start value.
So you can change your code to forbid the getter:
```
impl->progressAnim.target(cpgf::createAccessor(impl.get(), 0, &ProgressBarImpl::progressAnimValue), startValue, endValue)
```
Note how I changed the setter to 0.

However, I admit that it's quite confusing. I will investigate to see whether to change the code to use the start value no matter there is the getter or not, or emphasis it in the document.

You can read more in the last part in the document "Tweening large amount of properties at once in CPU data cache friendly manner"

http://www.cpgf.org/document/cpgf-tween-library.html

Also, I'm working on a game engine, which uses a lot of tween and callback library, you may read the code here,

https://github.com/wqking/gincu

Also, there is one place that uses the start value, in the transition code,

https://github.com/wqking/gincu/blob/master/src/transition/gtransitionfadeinout.cpp

**Comment by wqking** [comment]
Hi, just FYI, I have changed the code to always use the from value no matter the accessor is readable or not. I think it's more logical and less confusing.
Both develop and master branches are updated.

**Comment by nko12** [comment]
Oh cool, okay, that sounds good. I'll get back to you later to let you know how it's working.
