### ISSUE TITLE
How to get results from char* modifying methods ?

### ISSUE THREAD

**Issue by ErrorFlexXx** [cpgf/cpgf#81]
Hello,

I tried to call a c function that modifies a string that is passed by char*.
Is it possible, to get the result in a python script using that function ?
```cpp
GDefineMetaGlobal()
._method("mysql_real_escape_string", &mysql_real_escape_string)
```

MySQL function header is:
```cpp
unsigned long
mysql_real_escape_string(
              MYSQL *mysql,
              char *to,const char *from,
              unsigned long length);
```

I'm calling this function with the following python script, but the string passed as to is not changed from the function call.

```python
escapedLoginname = str("")
originalLoginname = str("HelloWorld")
i = mysql_real_escape_string(handle, escapedLoginname, originalLoginname, len(originalLoginname))
```

I also tried to use the cpgf Byte Array. But I don't know a way to get a python string out of an cpgf Byte Array.

**Comment by wqking** [comment]
Your code doesn't work because the script string is passed by value.

The solution is GMetaByteArray.
http://www.cpgf.org/document/script-binding-builtin-library-meta-byte-array.html

There is example how to pass reference from script to C++ using byte array.
http://www.cpgf.org/document/script-binding-useful-technology-tip-trick-caveat.html

So you can get the data from C++ back to script via function parameter. However, `GMetaByteArray::getPointer` returns void * and can't convert to string, so you need to write an auxilliary function to convert it to string.
For example, pseudo code,
```
std::string convertByteArrayToString(const GMetaByteArray * byteArray)
{
	return (char *)(byteArray->getPointer());
}
```

**Comment by wqking** [comment]
Another ultra-mate solution is, just write an auxiliary  C++ function to wrap mysql_real_escape_string to not to return value via parameters. :)

**Comment by ErrorFlexXx** [comment]
Many thanks!
I solved it now by creating a wrapper class for some mysql functions. Scripting live is much easier know, so I can use mysql without much script overhead.

Perfect, thanks :)
